apiVersion: apps/v1
kind: Deployment
metadata: 
  name: docker-k8s-user-deployment
  labels: 
    app: docker-k8s-user 
spec: 
    replicas: 1
    selector: 
      matchLabels:
        app: docker-k8s-user
      spec: 
       containers: 
       - name: docker-k8s-user
         image: harini98/login
         ports:
         - containerPort: 8077
    
    
    
    