apiVersion: apps/v1
kind: Deployment
metadata: 
  name: docker-k8s-product-deployment
  labels: 
    app: docker-k8s-product 
    
spec: 
    replicas: 1
    selector: 
      matchLabels:
        app: docker-k8s-product
      spec: 
       containers: 
       - name: docker-k8s-product
         image: harini98/product
         ports:
         - containerPort: 8078
    